### ISSUE TITLE
JuMP at conferences: ROADEF 2018?

### ISSUE THREAD

**Issue by dourouc05** [JuliaOpt/juliaopt.github.io#127]
Is there any guidelines about which conferences should be cited on the website? I'm asking because there was a special session about JuMP at ROADEF 2018 (French conference, not really international), organised by @xgandibleux: http://roadef2018.labsticc.fr/wp/?page_id=53.

**Comment by odow** [comment]
Not really. For informs we made a list of talks on the home page, and then moved them to the separate page after the conference.

Feel free to make a PR copying the informs page if you want. 

We're looking at redoing the website, so it'd be good to have more content of this sort of thing. We could make it a standard thing for conferences.

**Comment by odow** [comment]
Closed by #128
