### ISSUE TITLE
contributors

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/juliaopt.github.io#18]
Instead of a formal list of members, what about a "world of juliaopt" (https://github.com/jiahao/ijulia-notebooks/blob/master/montage_julia.jpg) graphic?
@jiahao, are there instructions posted for generating a montage like that?

**Comment by jiahao** [comment]
I think you can generate a montage like that with only small changes to the [World of Julia notebook](https://github.com/jiahao/ijulia-notebooks/blob/master/2014-06-30-world-of-julia.ipynb).

**Comment by barpit20** [comment]
@mlubin should I try to work on this? Might make a nice addition to the new website to be hosted on jump.dev

**Comment by mlubin** [comment]
This was an old suggestion and shouldn't really be a priority anymore, at least until we have a better idea of the structure of the new site.
