### ISSUE TITLE
really strip down solver table

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/juliaopt.github.io#19]
Instead of having a table at all, just have a list. Point users to another page (e.g. something like the table with the JuMP docs) to see precisely how to use the solvers. Allows us to be clearer about how to actually use them, but doesn't have this giant wall of a table on the JuliaOpt landing page.

Objections @tkelman @joehuchette ?

**Comment by joehuchette** [comment]
What's wrong with having the table on the landing page? I think it's sufficiently far down the page.

**Comment by tkelman** [comment]
I kinda like the table. It could be behind a link or something if you want the top-level page to be shorter

**Comment by IainNZ** [comment]
Yes behind a link is what I meant, table is def needed somewhere.
