### ISSUE TITLE
Example htmls on Juliaopt page are not latex rendered properly

### ISSUE THREAD

**Issue by Shuvomoy** [JuliaOpt/juliaopt.github.io#21]
The htmls of the IJulia notebooks provided on [http://www.juliaopt.org/notebooks/index.html]([http://www.juliaopt.org/notebooks/index.html]) are not latex rendered properly, many of the inline latex equations are just displayed as $E=m c^2$ (not only my notebooks, other ones too!). It might be better to provide the nbviewer links, they are latex rendered properly.

Best Regards,
Shuvo

**Comment by IainNZ** [comment]
My ideal would be to just figure out why its valid in Nbviewer but not valid here. I'm suspicious its an option that can be set for MathJax.
