### ISSUE TITLE
a "get started" guide for Julia/IJulia/JuMP

### ISSUE THREAD

**Issue by LaurentLessard** [JuliaOpt/juliaopt.github.io#36]
I'm teaching a class using Julia + IJulia + JuMP and I struggled to find a good guide for students to get up and running. This is what I used last year: [http://www.juliaopt.org/install.pdf](http://www.juliaopt.org/install.pdf) but it's quite out-of-date now and I wanted something current for my students.

I took the above document and modified it -- here is the [Google Doc version](https://docs.google.com/document/d/1nv6bvzbcBDRnVjxPusiTMXdwo7Ywooggp_o2W0IZuTg/edit?usp=sharing) I'll share with my students so I can make changes throughout the semester as necessary.

Not sure what to do with this... I'm sure others would find the guide useful, but I'm not sure if this is the best format for it. Perhaps a wiki? Thoughts and suggestions are welcome.

**Comment by mlubin** [comment]
I'd be happy to replace the install.pdf with your version since it's more recent. Making the google docs link public might also be useful for others who might want to tweak the instructions for their own course.

@chkwon, what do you think?

**Comment by chkwon** [comment]
It looks pretty good. And I agree that making Google docs public would work out well. Wiki-like approach!

If we actually make a wiki page at https://github.com/JuliaOpt/juliaopt.github.io/wiki, who will be able to make changes? Only JuliaOpt members, or anyone?

**Comment by chkwon** [comment]
It seems like we can allow any GitHub users edit wiki pages. But it looks quite painful to upload images. (need to upload images somewhere else)

I think public Google doc would be the best option for now.

**Comment by chkwon** [comment]
I forgot about mentioning Chapter 1 of my book. I actually share Chapter 1 publicly. 
http://www.chkwon.net/julia/book/juliabook-preview.pdf
This explains how to install Julia, JuMP, IJulia for Windows and Mac users. It's quite wordier than the Google doc version of @LaurentLessard. Perhaps we can link to my chapter as well.
