### ISSUE TITLE
solver table on juliaopt.org

### ISSUE THREAD

**Issue by harshangrjn** [JuliaOpt/juliaopt.github.io#99]
Creating an issue to have [Alpine.jl](https://github.com/lanl-ansi/Alpine.jl) appear in the list of optimization solvers in the table at juliaopt.org. Here are the ticks appropriate for Alpine.jl: 
Linear / Quadratic: Yes
Convex, Conic: Yes
Convex, smooth: No
Nonconvex: Yes (with global optimality guarantees) 
Integer: Yes
License: Open

**Comment by blegat** [comment]
The table is outdated, the Alpine should be added in the table in the JuMP doc, see https://github.com/JuliaOpt/JuMP.jl/pull/1856
